// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Wabisabi = Wabisabi || {};

/**
 * @constructor
 */
Wabisabi.Level = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Wabisabi.Level}
 */
Wabisabi.Level.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Wabisabi.Level=} obj
 * @returns {Wabisabi.Level}
 */
Wabisabi.Level.getRootAsLevel = function(bb, obj) {
  return (obj || new Wabisabi.Level).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Wabisabi.Level.prototype.worldSize = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Wabisabi.Level.startLevel = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} worldSize
 */
Wabisabi.Level.addWorldSize = function(builder, worldSize) {
  builder.addFieldFloat32(0, worldSize, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Wabisabi.Level.endLevel = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Wabisabi.Level.finishLevelBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.Wabisabi = Wabisabi;
